name: arotake
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pipreqs
  - pre-commit
  - ruff
  - mypy
  - mamba
  - cartopy
  - cftime
  - geopandas
  - h5netcdf
  - libnetcdf
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - proj
  - pyproj
  - regionmask
  - scipy
  - xarray
  - xesmf>=0.7
  - jupyter_client
  - jupyter_core
  - notebook
  - ipykernel
  - pip:
      - git+https://github.com/jankazil/Arotake
