name: arotake
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - cartopy
  - cftime
  - geopandas
  - h5netcdf
  - libnetcdf
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - proj
  - pyproj
  - regionmask
  - xarray
  - xesmf
  - pip:
      - git+https://github.com/jankazil/Arotake
